// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Athlete struct {
	ID             int32
	Name           string
	Grade          int8
	PersonalRecord sql.NullString
	Events         sql.NullString
	CreatedAt      sql.NullTime
}

type Meet struct {
	ID          int32
	Name        string
	MeetDate    time.Time
	Location    string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Result struct {
	ID        int32
	AthleteID int32
	MeetID    int32
	Time      string
	Place     sql.NullInt32
	CreatedAt sql.NullTime
}
